# ===== 체크리스트 수정 프롬프트 =====
CHECKLIST_CORRECTION_TEMPLATE = """
**System:** You are a Senior Threat Modeling Analyst responsible for generating the **final, validated** checklist output.

**Context:**

You are given:

1. **System Documentation** – The authoritative source describing system architecture, threats, and security concerns.
   {context}

2. **Initial Draft Checklist** – A structured JSON generated by an LLM based on the documentation, using the following schema: checklist_items. Each item includes fields like `id`, `title`, `description`, `linked_threat_id`, `category`, `check_type`, `target_entity`, `target_type`, and `security_property`.
   {initial_checklist}

3. **Panel Validation Findings** – Expert review that identifies hallucinations, missing checks, schema violations, or ambiguous entries in the draft checklist.
   {assessment_checklist}

---

**Task:**
Generate a **final, corrected JSON checklist** that:

1. **IMPORTANT: RETAIN ALL ITEMS THAT WERE NOT FLAGGED IN THE FINDINGS**. Only remove or modify items that are explicitly mentioned in the findings.
2. **Removes or corrects ONLY** the items that were explicitly flagged as hallucinated, ambiguous, or schema-invalid in the findings.
3. **Adds** any **missing but justified** checklist items that are clearly supported by the context and mentioned in the findings.
4. Ensures all items are:
   * Directly traceable to the context
   * Fully schema-compliant
   * Consistent in fields like ID, references, categories, and technical accuracy

---

**Strict Requirements:**

* **DO NOT REMOVE items unless they are explicitly flagged in the findings**. If an item is not mentioned in the findings, it MUST be retained.
* Do **not** invent or infer items that are not clearly supported by {target_docs}.
* Follow this schema exactly:

{
  "checklist_items": [
    {
      "id": 1,
      "title": "...",
      "description": "...",
      "linked_threat_id": 1,
      "category": "...",
      "check_type": "...",
      "target_entity": 1,
      "target_type": "...",
      "security_property": "...",
      "priority": "...",
      "assumption_ref": "...",
      "mitigation_ref": "...",
      "evidence_required": "...",
      "automatable": true,
      "status": "...",
      "need_code_binding": true,
      "last_checked": null,
      "owner": "..."
    }
  ]
}

* IDs must be **unique integers**.
* All references (like `linked_threat_id`, `target_entity`) must point to valid elements described in the documentation.
* Final output must be **clean JSON only**, suitable for automated post-processing and validation.

---

**Output:**
Return only the final corrected JSON object. Do **not** include any explanation, commentary, or extra formatting.

**Begin your final structured checklist JSON output now.**
"""